### ISSUE TITLE
Error: mime must be a string

### ISSUE THREAD

**Issue by rsmelo92** [numtel/meteor-cfs-image-resize#9]
Package working here as expected, but when I start the application it spams my console with this error: 
'Error: mime must be a string'

what should I do?

EDIT: It only works locally, when I deploy to heroku, it crashes my app!!
please help

**Comment by htmllab** [comment]
same issue here
W20170803-17:45:55.243(6)? (STDERR) /Users/mmd/e-learning-new/.meteor/local/build/programs/server/imageResizeWorker.CzkjYQKqHksCGq2mE.js:8
W20170803-17:45:55.298(6)? (STDERR)     if(error) throw error;
W20170803-17:45:55.298(6)? (STDERR)               ^
W20170803-17:45:55.299(6)? (STDERR) 
W20170803-17:45:55.299(6)? (STDERR) Error: mime must be a string
W20170803-17:45:55.300(6)? (STDERR)     at Jimp.throwError (/Users/mmd/.meteor/packages/numtel_cfs-image-resize/.0.0.4.1hoeyan++os+web.browser+web.cordova/npm/node_modules/jimp/index.js:82:43)
W20170803-17:45:55.301(6)? (STDERR)     at new Jimp (/Users/mmd/.meteor/packages/numtel_cfs-image-resize/.0.0.4.1hoeyan++os+web.browser+web.cordova/npm/node_modules/jimp/index.js:212:31)
W20170803-17:45:55.301(6)? (STDERR)     at process.<anonymous> (/Users/mmd/e-learning-new/.meteor/local/build/programs/server/imageResizeWorker.CzkjYQKqHksCGq2mE.js:7:3)
W20170803-17:45:55.301(6)? (STDERR)     at emitTwo (events.js:87:13)
W20170803-17:45:55.302(6)? (STDERR)     at process.emit (events.js:172:7)
W20170803-17:45:55.302(6)? (STDERR)     at internal/child_process.js:729:12
W20170803-17:45:55.302(6)? (STDERR)     at nextTickCallbackWith0Args (node.js:489:9)
W20170803-17:45:55.303(6)? (STDERR)     at process._tickCallback (node.js:418:13)
